### ISSUE TITLE
Openfermion version

### ISSUE THREAD

**Issue by jan-janssen** [tequilahub/tequila#196]
I get the following error message:
```
ModuleNotFoundError: No module named 'openfermion.chem'
```
For `openfermion==0.11` while the corresponding module is included in `openfermion>=1.0`. So I am wondering if the `requirements.txt` needs to be updated.

**Comment by kottmanj** [comment]
Thank you! That was indeed a typo, it should be "~=". Fixed it on master.
For the conda-forge recipe: Let me know if you get issues with psi4 in the tests (again a dependency issue that is fixed in the devel branch and will be gone in the next version. It does not really affect tq functionality).
