### ISSUE TITLE
How to save and load parameterized circuits?

### ISSUE THREAD

**Issue by jjgoings** [tequilahub/tequila#216]
Sorry if this isn't the best place to ask this. I was hoping to be able to save and load parameterized circuits. For example,
```python
import tequila as tq

geomstring="H 0.0 0.0 0.0\n\
              H 0.0 0.0 0.75"
mol = tq.Molecule(geometry=geomstring, backend='pyscf', basis_set='sto3g')

U = mol.make_ansatz(name='UCCSD')
print(U)

tq.circuit.qasm.export_open_qasm(U,filename='example_circuit.txt', variables={(1, 0, 1, 0) : 1.0, (1, 0):2.0})
```

gives the circuit

```
circuit:
X(target=(0,))
X(target=(1,))
FermionicExcitation(target=(0, 1, 2, 3), control=(), parameter=f([(1, 0, 1, 0)]))
FermionicExcitation(target=(0, 1, 2), control=(), parameter=f([(1, 0)]))
FermionicExcitation(target=(1, 2, 3), control=(), parameter=f([(1, 0)]))
```
and I've attached the saved qasm 2.0 file (`example_circuit.txt`.) But in the saved output it does not seem the variables are passed correctly, if at all. Is there a way to do this? I wasn't sure if I needed to pass in a `tq.Variable` object, but this does not seem to change anything and I get an error in `convert_to_open_qasm_2` saying `TypeError: Argument 'a' of type <class 'tequila.objective.objective.Variable'> is not a valid JAX type.`

Similarly, is there a way to read in parameterized circuits into Tequila?

If QASM is not the way to go, that's fine too ... just would like some way to save / load / share circuits.

**Comment by jjgoings** [comment]
[example_circuit.txt](https://github.com/tequilahub/tequila/files/8172791/example_circuit.txt)

**Comment by kottmanj** [comment]
Maybe also helpful: I Had to write a small serialiser once for a project, but since it was not able to handle all types of parameters I did not integrate it into tq. Maybe it gives some inspiration

https://github.com/kottmanj/genencoder

**Comment by jjgoings** [comment]
Hey thanks! What worked for me (thanks to your help) was

```python
import dill
import tequila as tq

geomstring="H 0.0 0.0 0.0\nH 0.0 0.0 0.75"
mol = tq.Molecule(geometry=geomstring, backend='pyscf', basis_set='sto6g')

# get the qubit hamiltonian
H = mol.make_hamiltonian()

# get the ansatz (circuit)
U = mol.make_ansatz(name='UCCSD')

with open("circuit.pickle", "wb") as f:
    dill.dump(U,f)

with open("circuit.pickle", "rb") as f:
    U2 = dill.load(f)

variables = U2.extract_variables()
M = {variables[i]:tq.Variable(i) for i in range(len(variables))}
U2 = U2.map_variables(M)

# define the expectation value
E = tq.ExpectationValue(H=H, U=U2)

# minimize the expectation value
result = tq.minimize(E, method='COBYLA')
print("VQE : {:+2.8}".format(result.energy))
```
