### ISSUE TITLE
Remove deprecated usage of numpy.float

### ISSUE THREAD

**Issue by doomspec** [tequilahub/tequila#286]
`numpy.float` has been deprecated since NumPy 1.20. When using Python 3.8 with conda automatically installed NumPy, there will be an error in the following code
```
import numpy
a = numpy.float(1)
``` 
The current version of tq includes many such usages
[https://github.com/search?q=repo%3Atequilahub%2Ftequila%20numpy.float&type=code](url)

Whenever these codes are executed, the program just stops.

We might need to change all `numpy.float` to `float` for higher version numpy

**Comment by kottmanj** [comment]
I'm just getting a warning, no error (numpy v.1.23.5). I potentially silenced them.
Updating is however a good idea. 
I'll put it on the todo list. If you have time to do it yourself, let me know.

**Comment by doomspec** [comment]
#287
