### ISSUE TITLE
Bump scipy to 1.14

### ISSUE THREAD

**Issue by ACE07-Sev** [tequilahub/tequila#361]
**Is your feature request related to a problem? Please describe.**

Greetings there,

Hope all are well. I would like to ask if you can bump the `scipy` version to `0.14` (latest version). I am trying to add support for your package to my package, however, given existing support for `pytket` and it needing `scipy==0.14` I can't make a venv with your package included.

**Describe the solution you'd like**
If possible, please bump the version in your requirements.txt to latest.

**Comment by kottmanj** [comment]
Hi, sure thing. The version restriction was just due to problems with other dependencies. I will check if that is fixed now and then upgrade.

**Comment by kottmanj** [comment]
Done
Should also reach pypi, once the release runner is through. 
Let us know if you have further issues :-)
